---
title: "'fasstr' Frequency Analysis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r options, include=FALSE}
knitr::opts_chunk$set(eval = nzchar(Sys.getenv("hydat_eval")))
```

The Flow Analysis Summary Statistics Tool for R (`fasstr`) is a set of [R](http://www.r-project.org) functions to tidy, summarize, analyze, trend, and visualize streamflow data. This package summarizes continuous daily mean streamflow data into various daily, monthly, annual, and long-term statistics, completes annual trends and frequency analyses, in both table and plot formats.

This vignette guide contains a guide on the volume frequency analysis functions found in `fasstr`.
See the HEC-SPP documentation for other information????

1. Functions and arguments (filtering)
2. General Settings (log, plotting positions,  max/min, ((year, time window)))
3. General Options (roll days, freqency ordinates??)
4. Extracting Volume DUration Data
Viewing the volume duration plot
Analystical Freuency analysis options (ft dist, and method)
...



